version: 1.0.{build}

clone_folder: c:\dev\openMVG

install:
  - git submodule update --init --recursive

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

build_script:
  - cd c:\dev\openMVG
  - md openMVG_build
  - cd openMVG_build
  # Configure:
  # - ceres - SCHUR_SPECIALIZATIONS set to OFF to speed up build time
  - cmake -DOpenMVG_BUILD_EXAMPLES=OFF -DOpenMVG_BUILD_TESTS=ON -DSCHUR_SPECIALIZATIONS=OFF ../src/
  # Build:
  - cmake --build .

test_script:
  - ctest -C %configuration% -V

build:
  parallel: true
  verbosity: minimal
