version: 1.0.{build}

clone_folder: c:\dev\openMVG

install:
  - git submodule update --init --recursive

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

before_build:
  - cd c:\dev\openMVG
  - md openMVG_build
  - cd openMVG_build
  # Configure:
  # - ceres - SCHUR_SPECIALIZATIONS set to OFF to speed up build time
  - cmake -DCMAKE_BUILD_TYPE=%configuration% -DOpenMVG_BUILD_EXAMPLES=OFF -DOpenMVG_BUILD_TESTS=ON -DSCHUR_SPECIALIZATIONS=OFF ../src/

build:
  project: c:\dev\openMVG\openMVG_Build\openMVG.sln
  parallel: true
  verbosity: minimal

test_script:
  - ctest -C %configuration% -V
